### ISSUE TITLE
Missing module (jaraco.collections) on python when upgrading to v2.8.0-beta

### ISSUE THREAD

**Issue by meepmeep** [JonnyWong16/plexpy#1581]
### Describe the Bug

After upgrading from 2.7.7 to 2.8.0-beta, tautulli is unable to start with en error message about "jaraco.collections".
I cleaned the pyc file, still an error.

### Steps to Reproduce

1. Upgrade to v2.8.0-beta
2. Wait .. Tautulli won't restart automatically
3. Try to launch from the cli : unable to start

### Expected Behavior

Seamless upgrade

### Tautulli Version

v2.8.0-beta

### Git Branch

from master to beta

### Git Commit Hash

Unable to get it (tautulli doesn't stard)

### Platform and Version

Ubuntu 20.04.3 LTS

### Python Version

3.8.10

### Browser and Version

Chrome 96

### Link to Logs

https://gist.github.com/meepmeep/724bc6709f9dac05543a8b5bf6c52bfb

**Comment by JonnyWong16** [comment]
Something is broken with your install.

The module is right here:
https://github.com/Tautulli/Tautulli/blob/v2.8.0-beta/lib/jaraco/collections.py

**Comment by meepmeep** [comment]
Maybe, but it's a fresh install from git clone and then ` git checkout refs/tags/v2.7.7`, moving the db and the config file, and then using the wegui to upgrade to 2.8-beta ..

**Comment by JonnyWong16** [comment]
I cannot reproduce. I still think you have something wrong on your system.

Ubuntu version and Python version.
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ python3 -V
Python 3.8.10
```

Cloning Tautulli.
```bash
$ git clone https://github.com/Tautulli/Tautulli.git
Cloning into 'Tautulli'...
remote: Enumerating objects: 36069, done.
remote: Counting objects: 100% (3851/3851), done.
remote: Compressing objects: 100% (2517/2517), done.
remote: Total 36069 (delta 1736), reused 3217 (delta 1181), pack-reused 32218
Receiving objects: 100% (36069/36069), 93.87 MiB | 15.58 MiB/s, done.
Resolving deltas: 100% (21425/21425), done.
```

Starting Tautulli (some log lines removed for brevity).
```bash
$ cd Tautulli
$ python3 Tautulli.py
2021-12-12 10:54:33 - INFO :: MainThread : Starting Tautulli v2.7.7
2021-12-12 10:54:33 - INFO :: MainThread : Linux 5.4.0-80-generic (#90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 - Ubuntu 20.04 focal)
...
2021-12-12 10:54:33 - INFO :: MainThread : Python 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
...
2021-12-12 10:54:33 - DEBUG :: MainThread : Git output: origin/master
...
2021-12-12 10:54:33 - INFO :: MainThread : Tautulli WebStart :: Starting Tautulli web server on http://0.0.0.0:8181/
...
2021-12-12 10:54:34 - INFO :: MainThread : Tautulli is ready!
```

Go through the setup wizard to set up Tautulli, then go to the Settings (Show Advanced) > Git Remote / Branch > Select `origin/beta` > Click "Checkout Branch" (some log lines removed for brevity).
```bash
2021-12-12 10:56:11 - INFO :: MainThread : Tautulli is switching the git branch...
2021-12-12 10:56:11 - INFO :: MainThread : Attempting to checkout git branch "origin/beta"
...
2021-12-12 10:56:13 - INFO :: MainThread : Tautulli is restarting...
...
2021-12-12 10:56:16 - INFO :: MainThread : Starting Tautulli v2.8.0-beta
2021-12-12 10:56:16 - INFO :: MainThread : Linux 5.4.0-80-generic (#90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 - Ubuntu 20.04 focal)
...
2021-12-12 10:56:16 - INFO :: MainThread : Python 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
...
2021-12-12 10:56:16 - DEBUG :: MainThread : Git output: origin/beta
...
2021-12-12 10:56:17 - INFO :: MainThread : Tautulli WebStart :: Starting Tautulli web server on http://0.0.0.0:8181/
...
2021-12-12 10:56:17 - INFO :: MainThread : Tautulli is ready!
```

**Comment by meepmeep** [comment]
```
meepmeep@Daenerys:~/RAID/plexpy2$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
meepmeep@Daenerys:~/RAID/plexpy2$ python -V
Python 3.8.10

```
 and 

```
meepmeep@Daenerys:~/RAID$ git clone https://github.com/Tautulli/Tautulli.git plexpy2
Cloning into 'plexpy2'...
[...]
Resolving deltas: 100% (21436/21436), done.
meepmeep@Daenerys:~/RAID$ cd plexpy2/
meepmeep@Daenerys:~/RAID/plexpy2$ python3 Tautulli.py
Traceback (most recent call last):
  File "Tautulli.py", line 39, in <module>
    import plexpy
  File "/home/meepmeep/RAID/plexpy2/plexpy/__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "/home/meepmeep/RAID/plexpy2/plexpy/activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "/home/meepmeep/RAID/plexpy2/plexpy/activity_processor.py", line 32, in <module>
    from plexpy import database
  File "/home/meepmeep/RAID/plexpy2/plexpy/database.py", line 31, in <module>
    from plexpy import helpers
  File "/home/meepmeep/RAID/plexpy2/plexpy/helpers.py", line 63, in <module>
    from plexpy import logger
  File "/home/meepmeep/RAID/plexpy2/plexpy/logger.py", line 23, in <module>
    import cherrypy
  File "/home/meepmeep/RAID/plexpy2/lib/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/home/meepmeep/RAID/plexpy2/lib/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/home/meepmeep/RAID/plexpy2/lib/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
ModuleNotFoundError: No module named 'jaraco.collections'
```

on a brand new directory.
Jaraco must be installed through pip3 ?

```
meepmeep@Daenerys:~/RAID/plexpy2$ pip3 list | grep jaraco
jaraco.classes                3.2.1
jaraco.collections            3.4.0
jaraco.functools              3.0.0
jaraco.itertools              2.0.1
jaraco.text                   3.6.0
```

**Comment by meepmeep** [comment]
I moved to snap. 
Issue solved with it.
