### ISSUE TITLE
Duplicate History & Log Entries

### ISSUE THREAD

**Issue by curtismangione** [JonnyWong16/plexpy#1590]
### Describe the Bug

When I view HISTORY it is showing duplicate line items for every watched show. Same user/starttime/duration etc. 2 identical line items for every played episode or movie.

### Steps to Reproduce

1. Go to HISTORY
2. Duplicate entries exist for a single event

### Tautulli Version

V2.7.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Windows 10 (10.0.19042)

### Python Version

	3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

### Browser and Version

Chrome 96

### Link to Logs

https://gist.github.com/curtismangione/4634687bfde9892c15d7663887becbd5

**Comment by samwiseg0** [comment]
```
Traceback (most recent call last):
  File "cherrypy\process\servers.py", line 225, in _start_http_thread
  File "cheroot\server.py", line 1795, in start
  File "cheroot\server.py", line 1754, in prepare
OSError: No socket could be created -- (('0.0.0.0', 8181): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted)

2021-12-08 04:31:12 - INFO    :: HTTPServer Thread-4 : [08/Dec/2021:04:31:12] ENGINE Bus STOPPING
2021-12-08 04:31:12 - INFO    :: HTTPServer Thread-4 : [08/Dec/2021:04:31:12] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8181)) already shut down
2021-12-08 04:31:12 - INFO    :: HTTPServer Thread-4 : [08/Dec/2021:04:31:12] ENGINE Bus STOPPED
2021-12-08 04:31:12 - INFO    :: HTTPServer Thread-4 : [08/Dec/2021:04:31:12] ENGINE Bus EXITING
2021-12-08 04:31:12 - INFO    :: HTTPServer Thread-4 : [08/Dec/2021:04:31:12] ENGINE Bus EXITED
2021-12-08 04:31:12 - ERROR   :: HTTPServer Thread-4 : Uncaught exception: Traceback (most recent call last):
  File "plexpy\logger.py", line 405, in new_run
  File "threading.py", line 870, in run
  File "cherrypy\process\servers.py", line 225, in _start_http_thread
  File "cheroot\server.py", line 1795, in start
  File "cheroot\server.py", line 1754, in prepare
OSError: No socket could be created -- (('0.0.0.0', 8181): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted)
```
You have multiple instances of Tautulli running. Please use discord for further support.
