### ISSUE TITLE
Tautulli fails to start unless local lib for jaraco is disabled and cherrypy is installed.

### ISSUE THREAD

**Issue by TheteSigma** [JonnyWong16/plexpy#1718]
### Describe the Bug

Gentoo LINUX Tautilli will no longer start, error with jaraco librar

### Steps to Reproduce

cd \opt\Tautulli
./start.sh
Starting Tautulli with python3.
Traceback (most recent call last):
  File "/opt/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/opt/Tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/opt/Tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 74, in <module>
    from jaraco.text import (
ImportError: cannot import name 'yield_lines' from 'jaraco.text' (/opt/Tautulli/lib/jaraco/text/__init__.py)

# disable jaraco included with Tautulli and use included with python
mv lib/jaraco/ lib/jaraco.old/
./start.sh
Starting Tautulli with python3.
Traceback (most recent call last):
  File "/opt/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/opt/Tautulli/plexpy/__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "/opt/Tautulli/plexpy/activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "/opt/Tautulli/plexpy/activity_processor.py", line 32, in <module>
    from plexpy import database
  File "/opt/Tautulli/plexpy/database.py", line 31, in <module>
    from plexpy import helpers
  File "/opt/Tautulli/plexpy/helpers.py", line 63, in <module>
    from plexpy import logger
  File "/opt/Tautulli/plexpy/logger.py", line 23, in <module>
    import cherrypy
  File "/opt/Tautulli/lib/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/opt/Tautulli/lib/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/opt/Tautulli/lib/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
ModuleNotFoundError: No module named 'jaraco.collections'

# Install cherrypy libs since included not working
emerge -av dev-python/cherrypy
./start.sh
Starting Tautulli with python3.

# With workaround it is currently running.

### Expected Behavior

./start.sh
Starting Tautulli with python3.

### Tautulli Version

v2.9.7 (2022-04-11)

### Git Branch

master

### Git Commit Hash

b0950abdd9baf8cfa4edd7549e85401e48529fc1

### Platform and Version

Gentoo

### Python Version

3.9.9

### Browser and Version

N/A

### Link to Logs

nothing was logged code error on startup

**Comment by TrevorAB** [comment]
Had the exact same issue, with the exact same outputs.
My VM provider had a support article that said

Remove a broken Python module: $rm -r ~/Tautulli/lib/jaraco/text/

After that, relaunch Tautulli as you would normally.
Mine restarted perfectly, and without any data loss.

Spent a couple of weeks looking for a solution but found nothing.
Not sure why it happened, but I know the above completely resolved my issue, so I thought I would share.

**Comment by TheteSigma** [comment]
# Issue still present

./start.sh
Starting Tautulli with python3.
Traceback (most recent call last):
  File "/opt/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/opt/Tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/opt/Tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 74, in <module>
    from jaraco.text import (
  File "/opt/Tautulli/lib/jaraco/text/__init__.py", line 227, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
  File "/usr/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Tautulli/lib/jaraco/text/Lorem ipsum.txt'

# This fixes the issue.
mv lib/jaraco lib/jarco.old

./start.sh
Starting Tautulli with python3.

**Comment by JonnyWong16** [comment]
I have no idea what's wrong with your install.

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Tautulli/lib/jaraco/text/Lorem ipsum.txt'
```

That file is included right here.

https://github.com/Tautulli/Tautulli/blob/master/lib/jaraco/text/Lorem%20ipsum.txt

**Comment by TheteSigma** [comment]
I suspect the first work around borked the update within Tautilli.
Renaming the /opt/Tautulli to /opt/Tautulli.old
Did a new git clone and moved the data back, everything now works.

**Comment by woodyl** [comment]
I just had this issue with both an update and a new installation of Tautulli on Gentoo 2.18.  Removing /lib/jaraco resolves the issue.
