### ISSUE TITLE
Discord Notification Test

### ISSUE THREAD

**Issue by frazz1234** [JonnyWong16/plexpy#1930]
### Describe the Bug

Just did the simple test notification whit the webhook and nothing is send. go this error : 

Tautulli NotificationHandler :: Notification thread exception: decoding str is not supported
Traceback (most recent call last):
    File "plexpy\request.py", line 178, in request_response2
    File "requests\models.py", line 960, in raise_for_status
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://discord.com/api/webhooks/1054059681812861049/fMAv5ZPXWcqX89MjZKs4QJwU6de2f7tRTRf0x53bxuR0ARzgV7Z-EhtXTPNzuQLMGa8N?wait=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "plexpy\notification_handler.py", line 78, in process_queue
    File "plexpy\notification_handler.py", line 430, in notify
    File "plexpy\notifiers.py", line 689, in send_notification
    File "plexpy\notifiers.py", line 937, in notify
    File "plexpy\notifiers.py", line 1178, in agent_notify
    File "plexpy\notifiers.py", line 944, in make_request
    File "plexpy\request.py", line 207, in request_response2
    File "plexpy\request.py", line 318, in server_message
TypeError: decoding str is not supported

### Tautulli Version

2.10.5

### Git Branch

master

### Git Commit Hash

	d7f6a1b186250bedbd46ae61888d80597b8ba976

### Platform and Version

Windows 10

### Python Version

3.9.13

### Browser and Version

edge

### Link to Logs

https://gist.github.com/frazz1234/5f46d575acccb720defef364d554551a

**Comment by JonnyWong16** [comment]
There's no bug here. You just sent too many notifications in a short amount of time.

```
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url
```
