### ISSUE TITLE
After update Tautulli doesn't start

### ISSUE THREAD

**Issue by ReDeViLzGz** [JonnyWong16/plexpy#1946]
### Describe the Bug

When I try to start Tautulli I receive this error:

```
# /usr/bin/python3 /path/to/tautulli/Tautulli.py --config /path/to/tautulli/config.ini --datadir /path/to/tautulli
Traceback (most recent call last):
  File "/path/to/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/path/to/tautulli/plexpy/__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "/path/to/tautulli/plexpy/activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "/path/to/tautulli/plexpy/activity_processor.py", line 32, in <module>
    from plexpy import database
  File "/path/to/tautulli/plexpy/database.py", line 31, in <module>
    from plexpy import helpers
  File "/path/to/tautulli/plexpy/helpers.py", line 24, in <module>
    import arrow
  File "/path/to/tautulli/lib/arrow/__init__.py", line 2, in <module>
    from .api import get, now, utcnow
  File "/path/to/tautulli/lib/arrow/api.py", line 12, in <module>
    from arrow.arrow import TZ_EXPR, Arrow
  File "/path/to/tautulli/lib/arrow/arrow.py", line 35, in <module>
    from arrow import formatter, locales, parser, util
  File "/path/to/tautulli/lib/arrow/formatter.py", line 10, in <module>
    from arrow import locales
  File "/path/to/tautulli/lib/arrow/locales.py", line 20, in <module>
    from typing_extensions import Literal
  File "/path/to/tautulli/lib/typing_extensions.py", line 193, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

### Steps to Reproduce

1. Update Tautulli to last version (2.11.1)
2. Try to start the service
3. Get that error

### Expected Behavior

Start Tautully normally

### Relevant Settings

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.7 (Ootpa)

# rpm -qa | grep python
python3-gobject-base-3.28.3-2.el8.x86_64
python3-chardet-3.0.4-7.el8.noarch
python3-urllib3-1.24.2-5.el8.noarch
python3-hawkey-0.63.0-11.1.el8.x86_64
platform-python-setuptools-39.2.0-6.el8.noarch
python3-dnf-4.7.0-11.el8.noarch
python3-pyudev-0.21.0-7.el8.noarch
python3-setools-4.3.0-3.el8.x86_64
python3-linux-procfs-0.7.0-1.el8.noarch
python3-dmidecode-3.12.2-15.el8.x86_64
python3-pip-wheel-9.0.3-22.el8.noarch
python3-dbus-1.2.4-15.el8.x86_64
python3-firewall-0.9.3-13.el8.noarch
python3-gpg-1.13.1-11.el8.x86_64
python3-idna-2.5-5.el8.noarch
python3-libs-3.6.8-48.el8_7.x86_64
python3-syspurpose-1.28.32-1.el8.x86_64
python3-schedutils-0.6-6.el8.x86_64
python3-slip-0.6.4-13.el8.noarch
python3-magic-5.33-21.el8.noarch
python3-decorator-4.2.1-2.el8.noarch
python3-subscription-manager-rhsm-1.28.32-1.el8.x86_64
python3-setuptools-wheel-39.2.0-6.el8.noarch
python3-configobj-5.0.6-11.el8.noarch
platform-python-pip-9.0.3-22.el8.noarch
python3-ethtool-0.14-5.el8.x86_64
python3-inotify-0.9.6-13.el8.noarch
platform-python-3.6.8-48.el8_7.x86_64
python3-libselinux-2.9-6.el8.x86_64
python3-pysocks-1.6.8-3.el8.noarch
python3-libsemanage-2.9-9.el8_6.x86_64
python3-librepo-1.14.2-3.el8.x86_64
python3-bind-9.11.36-5.el8_7.2.noarch
policycoreutils-python-utils-2.9-20.el8.noarch
python3-setuptools-39.2.0-6.el8.noarch
python3-rpm-4.14.3-24.el8_7.x86_64
python3-dnf-plugins-core-4.0.21-14.1.el8.noarch
python3-slip-dbus-0.6.4-13.el8.noarch
python3-nftables-0.9.3-26.el8.x86_64
python3-pyyaml-3.12-12.el8.x86_64
python3-perf-4.18.0-425.3.1.el8.x86_64
python3-policycoreutils-2.9-20.el8.noarch
python3-dateutil-2.6.1-6.el8.noarch
python3-ply-3.9-9.el8.noarch
python3-cloud-what-1.28.32-1.el8.x86_64
python3-requests-2.20.0-2.1.el8_1.noarch
python3-libcomps-0.1.18-1.el8.x86_64
python3-audit-3.0.7-4.el8.x86_64
python3-libdnf-0.63.0-11.1.el8.x86_64
python3-unbound-1.16.2-2.el8.x86_64
python3-pip-9.0.3-22.el8.noarch
python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64
python3-libxml2-2.9.7-15.el8.x86_64
python3-six-1.11.0-8.el8.noarch
python3-iniparse-0.4-31.el8.noarch

# pip3 show typing-extensions
Name: typing-extensions
Version: 4.1.1
Summary: Backported and Experimental Type Hints for Python 3.6+
Home-page: None
Author: None
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License: None
Location: /usr/local/lib/python3.6/site-packages
Requires: 

### Tautulli Version

2.11.1

### Git Branch

master

### Git Commit Hash

Can't see

### Platform and Version

Red Hat Enterprise Linux release 8.7 

### Python Version

3.6.8

### Browser and Version

Firefox 108.0.1

### Link to Logs

https://gist.github.com/ReDeViLzGz/e9d8910bc300995348e74da1b0216a59#file-gistfile1-txt

**Comment by ReDeViLzGz** [comment]
solved after update python to 3.8, sorry!
