### ISSUE TITLE
Error when starting Tautulli (ga4mp lib?)

### ISSUE THREAD

**Issue by nohareUK** [JonnyWong16/plexpy#2022]
### Describe the Bug

Tautulli fails to start after a fresh install into a new FreeBSD 12.3 jail.   Using the service command creates the pid file but checking listening ports and nothing is returned (no listener on 8181)

So as a test, attempting to start Tautulli using python on the command line generates the following (see Tracebacks near bottom of output):

# python Tautulli.py

/usr/local/share/Tautulli]# python Tautulli.py
2023-03-16 09:59:38 - INFO :: MainThread : Starting Tautulli v2.12.1
2023-03-16 09:59:38 - INFO :: MainThread : FreeBSD 12.3-RELEASE (FreeBSD 12.3-RELEASE #XigmaNAS: Sun Dec 12 20:35:51 CET 2021     root@de********1@********:/usr/obj/xigmanas/usr/src/amd64.amd64/sys/XIGMANAS-amd64 - FreeBSD 12.3)
2023-03-16 09:59:38 - INFO :: MainThread : Europe/London (UTC+0000)
2023-03-16 09:59:38 - INFO :: MainThread : Python 3.9.16 (main, Feb 19 2023, 01:13:52) [Clang 10.0.1 (gi********t@********:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611a
2023-03-16 09:59:38 - INFO :: MainThread : Program Dir: /usr/local/share/Tautulli
2023-03-16 09:59:38 - INFO :: MainThread : Config File: /usr/local/share/Tautulli/config.ini
2023-03-16 09:59:38 - INFO :: MainThread : Database File: /usr/local/share/Tautulli/tautulli.db
2023-03-16 09:59:38 - INFO :: MainThread : Checking if the database upgrades are required...
2023-03-16 09:59:38 - INFO :: MainThread : Checking if configuration upgrades are required...
2023-03-16 09:59:38 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /usr/local/share/Tautulli
2023-03-16 09:59:38 - DEBUG :: MainThread : Git output: 710dd7955f572a78213a131d4494629baf10aa13
2023-03-16 09:59:38 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /usr/local/share/Tautulli
2023-03-16 09:59:38 - DEBUG :: MainThread : Git output: origin/master
2023-03-16 09:59:38 - DEBUG :: MainThread : Using cached GitHub version data
2023-03-16 09:59:38 - DEBUG :: MainThread : Latest version is 710dd7955f572a78213a131d4494629baf10aa13
2023-03-16 09:59:38 - INFO :: MainThread : Tautulli is up to date
2023-03-16 09:59:38 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
**2023-03-16 09:59:38 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 324, in <module>
    main()
  File "/usr/local/share/Tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 581, in start
    analytics_event(name='install')
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 2862, in analytics_event
    event.set_event_param('platformVersion', common.PLATFORM_VERSION.split(';', 1)[0] if common.PLATFORM == 'Darwin' else common.PLATFORM_VERSION)
  File "/usr/local/share/Tautulli/lib/ga4mp/event.py", line 22, in set_event_param
    raise ValueError("Event parameter value cannot exceed 100 characters.")
ValueError: Event parameter value cannot exceed 100 characters.

Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 324, in <module>
    main()
  File "/usr/local/share/Tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 581, in start
    analytics_event(name='install')
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 2862, in analytics_event
    event.set_event_param('platformVersion', common.PLATFORM_VERSION.split(';', 1)[0] if common.PLATFORM == 'Darwin' else common.PLATFORM_VERSION)
  File "/usr/local/share/Tautulli/lib/ga4mp/event.py", line 22, in set_event_param
    raise ValueError("Event parameter value cannot exceed 100 characters.")
ValueError: Event parameter value cannot exceed 100 characters.**
[root@tautulli /usr/local/share/Tautulli]#

### Steps to Reproduce

1. created new jail
2. followed installation instructions for FreeBSD/TrueNAS platforms
3. attempted to start Tautulli using 'service tautulli start'
4. checked tcp listeners using 'sockstat -l'
5. move into /usr/local/share/Tautulli directory
6. deleted existing pid file (otherwise command below will detect existing pid file)
7. execute python Tautulli.py

### Expected Behavior

- Tautulli service daemon to successfully start with appropriate TCP-8181 listener running on the jail's interface
- 

### Relevant Settings

FreeBSD 12.3 (XigmaNAS Jail)

As per the installation instructions on git, the jail is installed with all necessary packages:
Python version is 3.9.16

other installed packages in jail include:

bash-5.2.15                    GNU Project's Bourne Again SHell
ca_root_nss-3.86               Root certificate bundle from the Mozilla Project
curl-7.87.0                    Command line tool and library for transferring data with URLs
expat-2.5.0                    XML 1.0 parser written in C
gettext-runtime-0.21.1         GNU gettext runtime libraries and programs
git-lite-2.39.2                Distributed source code management tool (lite flavor)
indexinfo-0.3.1                Utility to regenerate the GNU info page index
libedit-3.1.20221030,1         Command line editor library
libffi-3.4.4                   Foreign Function Interface
libidn2-2.3.4                  Implementation of IDNA2008 internationalized domain names
libnghttp2-1.48.0              HTTP/2.0 C Library
libpsl-0.21.1_6                C library to handle the Public Suffix List
libssh2-1.10.0_1,3             Library implementing the SSH2 protocol
libunistring-1.1               Unicode string library
mpdecimal-2.5.1                C/C++ arbitrary precision decimal floating point libraries
pcre2-10.40                    Perl Compatible Regular Expressions library, version 2
pkg-1.19.0                     Package manager
py39-cffi-1.15.1               Foreign Function Interface for Python calling C code
py39-cryptography-3.4.8,1      Cryptographic recipes and primitives for Python developers
py39-openssl-20.0.1,1          Python interface to the OpenSSL library
py39-pycparser-2.21            C parser in Python
py39-pycryptodomex-3.16.0      Cryptographic library for Python
py39-setuptools-63.1.0         Python packages installer
py39-six-1.16.0                Python 2 and 3 compatibility utilities
py39-sqlite3-3.9.16_7          Standard Python binding to the SQLite3 library (Python 3.9)
python-3.9_3,2                 "meta-port" for the default version of Python interpreter
python3-3_3                    Meta-port for the Python interpreter 3.x
python39-3.9.16                Interpreted object-oriented programming language
readline-8.2.0                 Library for editing command lines as they are typed
sqlite3-3.40.1,1               SQL database engine in a C library
zsh-5.9_1                      The Z shell

### Tautulli Version

2.12.1

### Git Branch

master

### Git Commit Hash

Git output: 710dd7955f572a78213a131d4494629baf10aa13

### Platform and Version

FreeBSD 12.3 

### Python Version

3.9.16

### Browser and Version

Version 111.0.5563.65 (Official Build) (64-bit)

### Link to Logs

https://gist.github.com/nohareUK/80a56c364ff22cd0d74007210a431e39

**Comment by JonnyWong16** [comment]
Fixed in v2.12.2.
