### ISSUE TITLE
Plex DVR recordings mpegts leads to inaccessibility 

### ISSUE THREAD

**Issue by throny** [JonnyWong16/plexpy#2070]
### Describe the Bug

After adding a library with Plex DVR recordings (MPEG-TS) to PMS, Tautulli won't load anymore:

```
400 Bad Request
Illegal key 'ys-api/mpegts/network'

Traceback (most recent call last):
  File "/app/lib/cherrypy/_cprequest.py", line 734, in process_headers
    self.cookie.load(value)
  File "/usr/lib/python3.10/http/cookies.py", line 532, in load
    self.__parse_string(rawdata)
  File "/usr/lib/python3.10/http/cookies.py", line 596, in __parse_string
    self.__set(key, rval, cval)
  File "/usr/lib/python3.10/http/cookies.py", line 488, in __set
    M.set(key, real_value, coded_value)
  File "/usr/lib/python3.10/http/cookies.py", line 353, in set
    raise CookieError('Illegal key %r' % (key,))
http.cookies.CookieError: Illegal key 'ys-api/mpegts/network'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/app/lib/cherrypy/_cprequest.py", line 666, in _do_respond
    self.process_headers()
  File "/app/lib/cherrypy/_cprequest.py", line 736, in process_headers
    raise cherrypy.HTTPError(400, str(exc))
cherrypy._cperror.HTTPError: (400, "Illegal key 'ys-api/mpegts/network'")
```

### Steps to Reproduce

1. Add Plex DVR
2. record something (MPEG-TS)

### Expected Behavior

Tautulli still being loaded, maybe just ignoring the mpeg-ts files

### Tautulli Version

2.12.3

### Git Branch

unknown

### Git Commit Hash

unknown

### Platform and Version

Truecharts / TrueNAS

### Python Version

unknown

### Browser and Version

Chrome 113

### Link to Logs

-

**Comment by JonnyWong16** [comment]
Nothing to do with the library.

Clear your browser cookies. It looks like you might be accessing multiple services from the same domain name with conflicting cookies.
