### ISSUE TITLE
Occasional SyntaxException When Loading Web App

### ISSUE THREAD

**Issue by joe-eklund** [JonnyWong16/plexpy#2097]
### Describe the Bug

Sometimes, when I first open my browser and navigate to my Tautulli web app I get an SyntaxException that is interleaved within the current activity. See the below log and screenshot.

Relevant log:

```
2023-07-06 14:59:38 - ERROR   :: CP Server Thread-12 : WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=150, after=146) ("data = defaultdict(lambda: 'Unknown', **session)\ns") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 69 char: 1
Traceback (most recent call last):
  File "/app/tautulli/lib/mako/lookup.py", line 241, in get_template
    return self._check(uri, self._collection[uri])
                            ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'current_activity_instance.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tautulli/lib/mako/pyparser.py", line 36, in parse
    return _ast_util.parse(code, "<unknown>", mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/_ast_util.py", line 91, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: AST constructor recursion depth mismatch (before=150, after=146)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/tautulli/plexpy/webserve.py", line 136, in serve_template
    template = _hplookup.get_template(templatename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/lookup.py", line 252, in get_template
    return self._load(srcfile, uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/lookup.py", line 313, in _load
    self._collection[uri] = template = Template(
                                       ^^^^^^^^^
  File "/app/tautulli/lib/mako/template.py", line 317, in __init__
    module = self._compile_from_file(path, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/template.py", line 393, in _compile_from_file
    code, module = _compile_text(self, data, filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/template.py", line 677, in _compile_text
    source, lexer = _compile(
                    ^^^^^^^^^
  File "/app/tautulli/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
           ^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/lexer.py", line 248, in parse
    if self.match_python_block():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/lexer.py", line 392, in match_python_block
    self.append_node(
  File "/app/tautulli/lib/mako/lexer.py", line 129, in append_node
    node = nodecls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/parsetree.py", line 158, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/ast.py", line 42, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/lib/mako/pyparser.py", line 38, in parse
    raise exceptions.SyntaxException(
```

### Steps to Reproduce

1. Have Tautulli running for a while.
2. Open up a browser and navigate to your webapp.
3. See error.

### Expected Behavior

No error.

### Screenshots

<img width="994" alt="tautulli" src="https://github.com/Tautulli/Tautulli/assets/8761687/0bad6329-8aab-493c-a1a4-0edd082f0665">

### Relevant Settings

- Accessing through Traefik.

### Tautulli Version

V2.12.4

### Git Branch

master

### Git Commit Hash

v2.12.4

### Platform and Version

Docker

### Python Version

3.11.3

### Browser and Version

Firefox 114.0.2 (64-bit)

### Link to Logs

https://gist.github.com/joe-eklund/467df58dbe5e0a4b7c84aa6a734da7fa

**Comment by JonnyWong16** [comment]
Upstream bug sqlalchemy/mako#378

There is an incompatibility with Python 3.11. Our official docker image `ghcr.io/tautulli/tautulli` use Python 3.9. There is nothing I can do about the Python version used in 3rd party docker images.

**Comment by joe-eklund** [comment]
I'm going to close this since the official image doesn't have this bug, and the image I am using has also implemented a workaround.
