### ISSUE TITLE
apscheduler.triggers preventing tautulli from starting

### ISSUE THREAD

**Issue by Jon87** [JonnyWong16/plexpy#2135]
### Describe the Bug

Noticed that tautulli wasn't running, tried restarting the service but getting an error message on start;

`Starting tautulli.
Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/share/Tautulli/lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "/usr/local/share/Tautulli/lib/apscheduler/schedulers/base.py", line 46,in <module>
    class BaseScheduler(six.with_metaclass(ABCMeta)):
  File "/usr/local/share/Tautulli/lib/apscheduler/schedulers/base.py", line 71,in BaseScheduler
    _trigger_plugins = {ep.name: ep for ep in entry_points()['apscheduler.triggers']}
KeyError: 'apscheduler.triggers'
/usr/local/etc/rc.d/tautulli: WARNING: failed to start tautulli`

### Steps to Reproduce

service tautulli start

### Expected Behavior

normal start

### Tautulli Version

v2.13.0

### Git Branch

master

### Git Commit Hash

289a8a23344931a295f88a21e56ae8feadaf525d

### Platform and Version

TrueNAS

### Python Version

3.9.17

### Browser and Version

chrome

### Link to Logs

none generating

**Comment by cadavor** [comment]
Same here

**Comment by Pawliko** [comment]
Same problem with Python 3.8.10

**Comment by JonnyWong16** [comment]
Fixed in v2.13.1.
