### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by darkphetus** [JonnyWong16/plexpy#2136]
### Describe the Bug

Running Tautulli using user tautulli (uid=1000) and group tautulli (gid=1000)
2023-08-27 08:47:12 - INFO :: MainThread : Starting Tautulli v2.13.1
2023-08-27 08:47:12 - INFO :: MainThread : [Docker] Linux 5.4.0-156-generic (#173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 - Debian GNU/Linux 12 bookworm)
2023-08-27 08:47:12 - INFO :: MainThread : America/New_York (UTC-0400)
2023-08-27 08:47:12 - INFO :: MainThread : Python 3.9.17 (main, Aug 16 2023, 05:48:24) [GCC 12.2.0]
2023-08-27 08:47:12 - INFO :: MainThread : SQLite 3.40.1
2023-08-27 08:47:12 - INFO :: MainThread : Program Dir: /app
2023-08-27 08:47:12 - INFO :: MainThread : Config File: /config/config.ini
2023-08-27 08:47:12 - INFO :: MainThread : Database File: /config/tautulli.db
2023-08-27 08:47:12 - INFO :: MainThread : Checking if the database upgrades are required...
2023-08-27 08:47:12 - INFO :: MainThread : Checking if configuration upgrades are required...
2023-08-27 08:47:12 - DEBUG :: MainThread : Using cached GitHub version data
2023-08-27 08:47:12 - DEBUG :: MainThread : Latest version is 6d858367a4367e204f1cc02467c99546a5d8bc23
2023-08-27 08:47:12 - INFO :: MainThread : Tautulli is up to date
2023-08-27 08:47:12 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/Tautulli.py", line 324, in <module>
    main()
  File "/app/Tautulli.py", line 247, in main
    plexpy.start()
  File "/app/plexpy/__init__.py", line 557, in start
    threading.Thread(target=startup_refresh).start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Traceback (most recent call last):
  File "/app/Tautulli.py", line 324, in <module>
    main()
  File "/app/Tautulli.py", line 247, in main
    plexpy.start()
  File "/app/plexpy/__init__.py", line 557, in start
    threading.Thread(target=startup_refresh).start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

### Tautulli Version

2.13.1

### Git Branch

master

### Git Commit Hash

n/a

### Platform and Version

ubuntu 20.04

### Python Version

3.9.17

### Browser and Version

n/a

### Link to Logs

https://www.dropbox.com/scl/fi/d9my82ox7cgofntxla4ii/tautulli_logs.tar.gz?rlkey=baeevql9nb0kla8yd70atj2mr&dl=0

**Comment by darkphetus** [comment]
2.13.0 also experiences the same issue. I have reverted back to pulling 2.12.5 to get a running tautulli container again

**Comment by JonnyWong16** [comment]
I think that's a docker issue, not a Tautulli specific issue.

https://github.com/docker-library/python/issues/837#issuecomment-1599640563

**Comment by darkphetus** [comment]
Thank you for the heads up. I was able to install the latest version of tautulli after modifiying my ansible playbook to include the following parameter rather than forcing an update to docker (or libseccomp) that may affect other running containers on the system, which I was loathe to attempt.

```
security_opts:
      - "seccomp:unconfined"
```

It is my assumption that making a similar change to a docker-compose file will also bypass the issue seen above.

**Comment by jmlara** [comment]
Resolved same issue.  I was able to update to v2.15.0 adding 

```
security_opt:
      - seccomp:unconfined
```

to my docker-compose.yml.
