### ISSUE TITLE
issue starting Tautulli since recent update

### ISSUE THREAD

**Issue by phairplay** [JonnyWong16/plexpy#2138]
### Describe the Bug

Tautulli updated over night and now won't start. when manually starting I noticed the following

```
C:\Windows\system32>C:\Python37\python.exe C:\Tautulli\PlexPy.py
Traceback (most recent call last):
  File "C:\Tautulli\PlexPy.py", line 20, in <module>
    from Tautulli import main
  File "C:\Tautulli\Tautulli.py", line 39, in <module>
    import plexpy
  File "C:\Tautulli\plexpy\__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "C:\Tautulli\plexpy\activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "C:\Tautulli\plexpy\activity_processor.py", line 32, in <module>
    from plexpy import database
  File "C:\Tautulli\plexpy\database.py", line 31, in <module>
    from plexpy import helpers
  File "C:\Tautulli\plexpy\helpers.py", line 64, in <module>
    from plexpy import logger
  File "C:\Tautulli\plexpy\logger.py", line 23, in <module>
    import cherrypy
  File "C:\Tautulli\lib\cherrypy\__init__.py", line 66, in <module>
    from ._cperror import (
  File "C:\Tautulli\lib\cherrypy\_cperror.py", line 129, in <module>
    from more_itertools import always_iterable
  File "C:\Tautulli\lib\more_itertools\__init__.py", line 3, in <module>
    from .more import *  # noqa
  File "C:\Tautulli\lib\more_itertools\more.py", line 5, in <module>
    from functools import cached_property, partial, reduce, wraps
ImportError: cannot import name 'cached_property' from 'functools' (C:\Python37\lib\functools.py)
```

### Steps to Reproduce

1. starting the program

### Expected Behavior

to load as normal, everything as fine before a suspected update.

### Tautulli Version

v2.12.5

### Git Branch

master

### Git Commit Hash

n/a

### Platform and Version

Windows 10

### Python Version

3.7

### Browser and Version

Chrome

### Link to Logs

n/a

**Comment by JonnyWong16** [comment]
Please read the changelogs.

https://github.com/Tautulli/Tautulli/releases

> * Notes:
>    * Support for Python 3.7 has been dropped. The minimum Python version is now 3.8.
