### ISSUE TITLE
Database error: ambiguous column name: on_pause

### ISSUE THREAD

**Issue by jpoggi** [JonnyWong16/plexpy#2183]
### Describe the Bug

Hi,

I have just updated to the latest version of Docker's container of tautulli v2.13.2, and at the startup the container crash.

Here is my docker compose stack startup logs:

```
tautulli  | usermod: no changes
tautulli  | Running Tautulli using user tautulli (uid=1000) and group tautulli (gid=1000)
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Starting Tautulli v2.13.2
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : [Docker] Linux 5.15.0-87-generic (#97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 - Debian GNU/Linux 12 bookworm)
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Europe/Paris (UTC+0200)
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Python 3.9.18 (main, Oct 11 2023, 23:49:58) [GCC 12.2.0]
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : SQLite 3.40.1
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Program Dir: /app
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Config File: /config/config.ini
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Database File: /config/tautulli.db
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Checking if the database upgrades are required...
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Checking if configuration upgrades are required...
tautulli  | 2023-10-26 22:42:26 - DEBUG :: MainThread : Using cached GitHub version data
tautulli  | 2023-10-26 22:42:26 - DEBUG :: MainThread : Latest version is c215afbf84baafb1a2020c2dc6e36944a6de1504
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Tautulli is up to date
tautulli  | 2023-10-26 22:42:26 - INFO :: Thread-1 : Tautulli PlexTV :: Requesting resources for server...
tautulli  | 2023-10-26 22:42:26 - INFO :: Thread-1 : Tautulli PlexTV :: Pinging Plex.tv to refresh token.
tautulli  | 2023-10-26 22:42:26 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
tautulli  | 2023-10-26 22:42:26 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
tautulli  | 2023-10-26 22:42:26 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
tautulli  |   File "/app/Tautulli.py", line 324, in <module>
tautulli  |     main()
tautulli  |   File "/app/Tautulli.py", line 247, in main
tautulli  |     plexpy.start()
tautulli  |   File "/app/plexpy/__init__.py", line 569, in start
tautulli  |     notifiers.check_browser_enabled()
tautulli  |   File "/app/plexpy/notifiers.py", line 4483, in check_browser_enabled
tautulli  |     for n in get_notifiers():
tautulli  |   File "/app/plexpy/notifiers.py", line 510, in get_notifiers
tautulli  |     result = db.select(
tautulli  |   File "/app/plexpy/database.py", line 455, in select
tautulli  |     sql_results = self.action(query, args).fetchall()
tautulli  |   File "/app/plexpy/database.py", line 433, in action
tautulli  |     sql_result = c.execute(query, args)
tautulli  | sqlite3.OperationalError: ambiguous column name: on_pause
tautulli  | 
tautulli  | Traceback (most recent call last):
tautulli  |   File "/app/Tautulli.py", line 324, in <module>
tautulli  |     main()
tautulli  |   File "/app/Tautulli.py", line 247, in main
tautulli  |     plexpy.start()
tautulli  |   File "/app/plexpy/__init__.py", line 569, in start
tautulli  |     notifiers.check_browser_enabled()
tautulli  |   File "/app/plexpy/notifiers.py", line 4483, in check_browser_enabled
tautulli  |     for n in get_notifiers():
tautulli  |   File "/app/plexpy/notifiers.py", line 510, in get_notifiers
tautulli  |     result = db.select(
tautulli  |   File "/app/plexpy/database.py", line 455, in select
tautulli  |     sql_results = self.action(query, args).fetchall()
tautulli  |   File "/app/plexpy/database.py", line 433, in action
tautulli  |     sql_result = c.execute(query, args)
tautulli  | sqlite3.OperationalError: ambiguous column name: on_pause$
```

### Steps to Reproduce

1. Update to the v2.13.2 version of Tautulli's container.

### Expected Behavior

Tautulli to correctly startup :-)

### Relevant Settings

Here is some relevant informations.

```
john@doe:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
john@doe:~$ docker compose version
Docker Compose version v2.23.0
```

```
services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli:v2.13.2
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - '8181:8181'
    environment:
      TZ: Europe/Paris
      PUID: 1000
      PGID: 1000
    volumes:
      - ~/config:/config
```

### Tautulli Version

v2.13.2

### Git Branch

master

### Git Commit Hash

6d858367a4367e204f1cc02467c99546a5d8bc23

### Platform and Version

Ubuntu Server 22.04.3

### Python Version

3.9.18

### Browser and Version

Firefox 119.0

### Link to Logs

https://gist.github.com/jpoggi/db3eef517e1b7fbfa59606ee1acce31f

**Comment by jpoggi** [comment]
I have rollback to the previous version used, v2.13.1 and the container is correctly starting.

By the way the commit hash is from the previous version too, I can't get it from the latest version as the container crash.

**Comment by JonnyWong16** [comment]
https://discord.com/channels/183396325142822912/1161326470040395807/1161382647352803409

**Comment by jpoggi** [comment]
Ok not a problem with Tautulli directly but the database.

Solution found on Discord.

```
DROP TABLE notify_log
```

Thanks @JonnyWong16

**Comment by fryfrog** [comment]
This sorted me out too, thanks!

**Comment by bitchkat** [comment]
I fixed it a separate way before seeing this issue

`def qualify_notifier(notifier):
    return 'notifiers.' + notifier

def get_notifiers(notifier_id=None, notify_action=None):
    notify_actions = get_notify_actions()
    notify_actions = map(qualify_notifier, notify_actions)
`
Note: I'm not a python expert by any means so I'm sure that can be simplified.

**Comment by garrettben** [comment]
@JonnyWong16 Thanks, I only checked open issues before I opened mine, will check closed next time.  Fixed with `DROP TABLE notify_log`

**Comment by JamminR** [comment]
I'm not running Python or SQL.
I'm running the Tautulli Win exe.
How does someone with the above statements fix this error other than running an old version?
I clicked the discord link and this appears -
![image](https://github.com/Tautulli/Tautulli/assets/3392170/2118c36c-c5df-40d9-bf6c-72284b469e85)
Do we wait until a new release is compiled?

**Comment by JonnyWong16** [comment]
Use [DB Browser for SQLite](https://sqlitebrowser.org/).
