### ISSUE TITLE
sqlite3.OperationalError after upgrade to v2.13.2

### ISSUE THREAD

**Issue by garrettben** [JonnyWong16/plexpy#2187]
### Describe the Bug

After upgrading Tautulli from v2.13.1 to v2.13.2, I get a DB error that stops Tautulli from starting:

2023-10-28 21:14:49 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2023-10-28 21:14:49 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
2023-10-28 21:14:49 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/tautulli_venv/Tautulli/./PlexPy.py", line 24, in <module>
    main()
  File "/opt/tautulli_venv/Tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/opt/tautulli_venv/Tautulli/plexpy/__init__.py", line 569, in start
    notifiers.check_browser_enabled()
  File "/opt/tautulli_venv/Tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
    for n in get_notifiers():
  File "/opt/tautulli_venv/Tautulli/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
  File "/opt/tautulli_venv/Tautulli/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
  File "/opt/tautulli_venv/Tautulli/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
sqlite3.OperationalError: ambiguous column name: on_pause

Traceback (most recent call last):
  File "/opt/tautulli_venv/Tautulli/./PlexPy.py", line 24, in <module>
    main()
  File "/opt/tautulli_venv/Tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/opt/tautulli_venv/Tautulli/plexpy/__init__.py", line 569, in start
    notifiers.check_browser_enabled()
  File "/opt/tautulli_venv/Tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
    for n in get_notifiers():
  File "/opt/tautulli_venv/Tautulli/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
  File "/opt/tautulli_venv/Tautulli/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
  File "/opt/tautulli_venv/Tautulli/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
sqlite3.OperationalError: ambiguous column name: on_pause

### Steps to Reproduce

1. Start on v2.13.1, and verify Tautulli will start correctly running ./PlexPy.py at the tautulli user in a venv
2. git checkout  v2.13.2
3. After running ./PlexPy.py I get the described error.
4. git checkout v2.13.1
5. Start Tautulli again, and it works as expected.

### Expected Behavior

I noticed this when I upgraded from the web interface on Ubuntu Linux.  The steps to reproduce and description of the behavior are above.

### Tautulli Version

v2.13.2

### Git Branch

master

### Git Commit Hash

c215afbf84baafb1a2020c2dc6e36944a6de1504

### Platform and Version

Ubuntu 22.04.3 LTS

### Python Version

Python 3.10.12

### Browser and Version

118.0.2 (64-bit) on Ubuntu

### Link to Logs

https://gist.github.com/garrettben/5b0c651290703e1cd664099b8c159ed7

**Comment by JonnyWong16** [comment]
Duplicate #2185, #2184, #2183.
