### ISSUE TITLE
get_notifiers bug in commit fdc1dd3

### ISSUE THREAD

**Issue by threevil** [JonnyWong16/plexpy#2188]
### Describe the Bug

Commit fdc1dd3 3 weeks ago appears to have introduced a bug in notifiers.py with the modified SQL query in get_notifiers on lines 510-519. Due to the fact that on_pause exists in both the notifiers table as well as the notify_log table, the where portion of the query creates an ambiguous field name.

I was able to resolve the bug locally by making the following change to the query:

    result = db.select(
        (
            "SELECT notifiers.id, notifiers.agent_id, notifiers.agent_name, notifiers.agent_label, notifiers.friendly_name, %s, "
            "MAX(notify_log.timestamp) AS last_triggered, notify_log.success AS last_success "
            "FROM notifiers "
            "LEFT OUTER JOIN notify_log ON notifiers.id = notify_log.notifier_id "
            "%s "
            "GROUP BY notifiers.id"
        ) % (', '.join(['notifiers.' + action for action in notify_actions]), where), args=args
    )

### Steps to Reproduce

1. Have notifiers created
2. Start the linuxserver docker for tautulli

### Expected Behavior

The query should complete as expected without the error.

### Screenshots

2023-11-01T03:33:17.731335992Z 2023-10-31 23:33:17 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2023-11-01T03:33:17.733621514Z 2023-10-31 23:33:17 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
2023-11-01T03:33:17.736217251Z 2023-10-31 23:33:17 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
2023-11-01T03:33:17.736238511Z   File "/app/tautulli/Tautulli.py", line 324, in <module>
2023-11-01T03:33:17.736246336Z     main()
2023-11-01T03:33:17.736252608Z   File "/app/tautulli/Tautulli.py", line 247, in main
2023-11-01T03:33:17.736258669Z     plexpy.start()
2023-11-01T03:33:17.736274299Z   File "/app/tautulli/plexpy/__init__.py", line 569, in start
2023-11-01T03:33:17.736280300Z     notifiers.check_browser_enabled()
2023-11-01T03:33:17.736285921Z   File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
2023-11-01T03:33:17.736292633Z     for n in get_notifiers():
2023-11-01T03:33:17.736302071Z              ^^^^^^^^^^^^^^^
2023-11-01T03:33:17.736311519Z   File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
2023-11-01T03:33:17.736317520Z     result = db.select(
2023-11-01T03:33:17.736322870Z              ^^^^^^^^^^
2023-11-01T03:33:17.736328742Z   File "/app/tautulli/plexpy/database.py", line 455, in select
2023-11-01T03:33:17.736334122Z     sql_results = self.action(query, args).fetchall()
2023-11-01T03:33:17.736339512Z                   ^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-01T03:33:17.736385108Z   File "/app/tautulli/plexpy/database.py", line 433, in action
2023-11-01T03:33:17.736397171Z     sql_result = c.execute(query, args)
2023-11-01T03:33:17.736403242Z                  ^^^^^^^^^^^^^^^^^^^^^^
2023-11-01T03:33:17.736408742Z sqlite3.OperationalError: ambiguous column name: on_pause
2023-11-01T03:33:17.736414183Z 
2023-11-01T03:33:17.736419403Z Traceback (most recent call last):
2023-11-01T03:33:17.736424683Z   File "/app/tautulli/Tautulli.py", line 324, in <module>
2023-11-01T03:33:17.736431776Z     main()
2023-11-01T03:33:17.736437316Z   File "/app/tautulli/Tautulli.py", line 247, in main
2023-11-01T03:33:17.736442937Z     plexpy.start()
2023-11-01T03:33:17.736448217Z   File "/app/tautulli/plexpy/__init__.py", line 569, in start
2023-11-01T03:33:17.736497841Z     notifiers.check_browser_enabled()
2023-11-01T03:33:17.736512188Z   File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
2023-11-01T03:33:17.737020467Z     for n in get_notifiers():
2023-11-01T03:33:17.737039803Z              ^^^^^^^^^^^^^^^
2023-11-01T03:33:17.737046876Z   File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
2023-11-01T03:33:17.737143118Z     result = db.select(
2023-11-01T03:33:17.737156603Z              ^^^^^^^^^^
2023-11-01T03:33:17.737165430Z   File "/app/tautulli/plexpy/database.py", line 455, in select
2023-11-01T03:33:17.737218360Z     sql_results = self.action(query, args).fetchall()
2023-11-01T03:33:17.737245892Z                   ^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-01T03:33:17.737259798Z   File "/app/tautulli/plexpy/database.py", line 433, in action
2023-11-01T03:33:17.737312888Z     sql_result = c.execute(query, args)
2023-11-01T03:33:17.737327175Z                  ^^^^^^^^^^^^^^^^^^^^^^
2023-11-01T03:33:17.737340060Z sqlite3.OperationalError: ambiguous column name: on_pause

### Tautulli Version

2.13.2

### Git Branch

master

### Git Commit Hash

v2.13.2

### Platform and Version

Docker, linuxserver

### Python Version

3.11.6 (main, Oct 4 2023, 06:22:18) [GCC 12.2.1 20220924]

### Browser and Version

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

### Link to Logs

https://gist.github.com/threevil/d76cc81e99678db3315fb687db6138d4

**Comment by JonnyWong16** [comment]
Duplicate #2187, #2185, #2184, #2183.
