### ISSUE TITLE
v2.13.2 Tautulli Database :: Database error: ambiguous column name: on_pause

### ISSUE THREAD

**Issue by peva3** [JonnyWong16/plexpy#2200]
### Describe the Bug

Updated my docker image to the latest version and Tautulli no longer loads, here's the only error in the logs:

```
2023-11-07 16:48:40 - INFO :: Thread-1 (startup_refresh) : Tautulli PlexTV :: Requesting resources for server...
2023-11-07 16:48:40 - INFO :: Thread-1 (startup_refresh) : Tautulli PlexTV :: Pinging Plex.tv to refresh token.
2023-11-07 16:48:40 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2023-11-07 16:48:40 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
2023-11-07 16:48:40 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 324, in <module>
    main()
  File "/app/tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/app/tautulli/plexpy/__init__.py", line 572, in start
    notifiers.check_browser_enabled()
  File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
    for n in get_notifiers():
             ^^^^^^^^^^^^^^^
  File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
             ^^^^^^^^^^
  File "/app/tautulli/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
                 ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: ambiguous column name: on_pause

Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 324, in <module>
    main()
  File "/app/tautulli/Tautulli.py", line 247, in main
    plexpy.start()
  File "/app/tautulli/plexpy/__init__.py", line 572, in start
    notifiers.check_browser_enabled()
  File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
    for n in get_notifiers():
             ^^^^^^^^^^^^^^^
  File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
             ^^^^^^^^^^
  File "/app/tautulli/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tautulli/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
                 ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: ambiguous column name: on_pause
2023-11-07 16:48:41 - INFO :: Thread-1 (startup_refresh) : Tautulli Config :: Writing configuration to file
2023-11-07 16:48:41 - INFO :: Thread-1 (startup_refresh) : Tautulli PlexTV :: Using user-defined URL.

```

### Tautulli Version

v2.13.2

### Git Branch

master

### Git Commit Hash

32cf26884b4dcc7fa1aa26260d99689b922deedd

### Platform and Version

Debian

### Python Version

3.11.6

### Browser and Version

Version 119.0.6045.124 (Official Build) (64-bit)

### Link to Logs

https://gist.github.com/pmwoodward3/4ad7fc0b0295a337eca25f7d35a55b01

**Comment by JonnyWong16** [comment]
Duplicate #2187, #2185, #2184, #2183.
