### ISSUE TITLE
Tautulli Scheduled Tasks Error ! AttributeError: 'NoneType' object has no attribute 'next_run_time'

### ISSUE THREAD

**Issue by zer0de-r00tSec** [JonnyWong16/plexpy#2228]
### Describe the Bug

On the webpage i see a few minutes after restart.

`Tautulli Scheduled Tasks
Error !
AttributeError: 'NoneType' object has no attribute 'next_run_time'`

and at the Logs

`2023-12-27 22:05:22 - ERROR :: CP Server Thread-14 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body`

### Steps to Reproduce

nothing, only restart the container, wait a moment, refresh the site, tada error

### Tautulli Version

v2.13.4

### Git Branch

master

### Git Commit Hash

d019efcf911b4806618761c2da48bab7d04031ec

### Platform and Version

 	[Docker] Linux 6.1.64-Unraid (#1 SMP PREEMPT_DYNAMIC Wed Nov 29 12:48:16 PST 2023 - Debian GNU/Linux 12 bookworm)

### Python Version

3.9.18 (main, Nov 29 2023, 05:59:34) [GCC 12.2.0]

### Browser and Version

FF for Linux-Mint 121.0 (64-Bit)

### Link to Logs

https://gist.github.com/zer0de-r00tSec/8b9ad50c382047a374c153dbf6358592

**Comment by JonnyWong16** [comment]
Incomplete logs.

**Comment by zer0de-r00tSec** [comment]
u rly want 4,5MB Log file pasted her? 
this part is not enought?

**Comment by JonnyWong16** [comment]
Yes.

**Comment by hirenshah** [comment]
I just noticed the same errors and found that it only occurs after disabling "Check for Tautulli Updates" and also results in the "TAUTULLI SCHEDULED TASKS" section breaking.  If I re-enable "Check for Tautulli Updates" everything is fine again.

```
2024-01-06 11:13:21 - INFO    :: CP Server Thread-9 : Retrieving latest version information from GitHub
2024-01-06 11:13:21 - DEBUG   :: CP Server Thread-9 : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master
2024-01-06 11:13:22 - INFO    :: CP Server Thread-14 : Tautulli Config :: Writing configuration to file
2024-01-06 11:13:22 - DEBUG   :: CP Server Thread-9 : Latest version is d019efcf911b4806618761c2da48bab7d04031ec
2024-01-06 11:13:22 - INFO    :: CP Server Thread-9 : Tautulli is up to date
2024-01-06 11:13:45 - INFO    :: CP Server Thread-12 : Tautulli Config :: Writing configuration to file
2024-01-06 11:13:45 - INFO    :: CP Server Thread-12 : Removed background task: Check GitHub for updates
2024-01-06 11:13:46 - ERROR   :: CP Server Thread-7 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:13:46 - INFO    :: CP Server Thread-15 : Tautulli Config :: Writing configuration to file
2024-01-06 11:14:32 - INFO    :: CP Server Thread-15 : Tautulli Config :: Writing configuration to file
2024-01-06 11:14:33 - INFO    :: CP Server Thread-15 : Re-scheduled background task: Check for Plex updates
2024-01-06 11:14:33 - INFO    :: CP Server Thread-15 : Re-scheduled background task: Refresh users list
2024-01-06 11:14:33 - INFO    :: CP Server Thread-15 : Re-scheduled background task: Refresh libraries list
2024-01-06 11:14:34 - ERROR   :: CP Server Thread-14 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:14:35 - INFO    :: CP Server Thread-12 : Tautulli Config :: Writing configuration to file
2024-01-06 11:14:37 - INFO    :: CP Server Thread-11 : Tautulli Config :: Writing configuration to file
2024-01-06 11:14:38 - ERROR   :: CP Server Thread-7 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:14:39 - INFO    :: CP Server Thread-12 : Tautulli Config :: Writing configuration to file
2024-01-06 11:15:07 - ERROR   :: CP Server Thread-14 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:15:10 - INFO    :: CP Server Thread-11 : Tautulli Config :: Writing configuration to file
2024-01-06 11:18:26 - INFO    :: CP Server Thread-15 : Tautulli Config :: Writing configuration to file
2024-01-06 11:18:26 - INFO    :: CP Server Thread-15 : Scheduled background task: Check GitHub for updates
2024-01-06 11:18:28 - INFO    :: CP Server Thread-9 : Tautulli Config :: Writing configuration to file
2024-01-06 11:18:45 - INFO    :: CP Server Thread-6 : Tautulli Config :: Writing configuration to file
2024-01-06 11:18:56 - INFO    :: CP Server Thread-13 : Tautulli Config :: Writing configuration to file
2024-01-06 11:18:56 - INFO    :: CP Server Thread-13 : Removed background task: Check GitHub for updates
2024-01-06 11:18:56 - ERROR   :: CP Server Thread-12 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:18:58 - INFO    :: CP Server Thread-9 : Tautulli Config :: Writing configuration to file
2024-01-06 11:19:01 - ERROR   :: CP Server Thread-13 : WebUI :: Mako template render error: 'NoneType' object has no attribute 'next_run_time'
Traceback (most recent call last):
  File "/app/plexpy/webserve.py", line 143, in serve_template
    return template.render(http_root=http_root, server_name=server_name, cache_param=cache_param,
  File "/app/lib/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/app/lib/mako/runtime.py", line 874, in _render
    _render_context(
  File "/app/lib/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/lib/mako/runtime.py", line 938, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/app/lib/mako/runtime.py", line 948, in _render_error
    result = template.error_handler(context, error)
  File "/app/lib/mako/runtime.py", line 936, in _exec_template
    callable_(context, *args, **kwargs)
  File "scheduler_table_html", line 35, in render_body
AttributeError: 'NoneType' object has no attribute 'next_run_time'
2024-01-06 11:19:04 - INFO    :: CP Server Thread-7 : Tautulli Config :: Writing configuration to file
2024-01-06 11:19:10 - INFO    :: CP Server Thread-15 : Tautulli Config :: Writing configuration to file
2024-01-06 11:19:10 - INFO    :: CP Server Thread-15 : Scheduled background task: Check GitHub for updates
2024-01-06 11:19:11 - INFO    :: CP Server Thread-14 : Tautulli Config :: Writing configuration to file
```

**Comment by imran0** [comment]
I can confirm I also experience the same error raised by the OP. Using @hirenshah's workaround has fixed the issue.
