### ISSUE TITLE
Docker Compose - ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jamie-2bit** [JonnyWong16/plexpy#2242]
Tautulli v2.13.4 will not start using docker and just cycles through the following:

usermod: no changes
Running Tautulli using user tautulli (uid=1000) and group tautulli (gid=1000)
Traceback (most recent call last):
  File "/app/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/plexpy/__init__.py", line 86, in <module>
    from plexpy import webstart
  File "/app/plexpy/webstart.py", line 32, in <module>
    from plexpy import webauth
  File "/app/plexpy/webauth.py", line 30, in <module>
    import jwt
  File "/app/lib/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/app/lib/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/app/lib/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/app/lib/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### Tautulli Version

v2.13.4

### Git Branch

master

### Git Commit Hash

not available

### Platform and Version

Docker - Using Compose

### Python Version

Docker - Using Compose

### Browser and Version

Chrome

### Link to Logs

See Above

**Comment by JonnyWong16** [comment]
Duplicate #2189
